### ISSUE TITLE
Invalid assignment location: "PairwiseListMatrices.t"

### ISSUE THREAD

**Issue by kescobo** [diegozea/PairwiseListMatrices.jl#7]
Trying to load up the package in Juno for the first time, while precompiling, and after a bunch of depwarnings:

```
ERROR: LoadError: LoadError: 
syntax: invalid assignment location "PairwiseListMatrices.t"
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:569
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:569
 [4] include(::String) at ./sysimg.jl:14
 [5] anonymous at ./<missing>:2
while loading /Users/kev/.julia/v0.6/PairwiseListMatrices/src/pairwiselistmatrix.jl, in expression starting on line 963
while loading /Users/kev/.julia/v0.6/PairwiseListMatrices/src/PairwiseListMatrices.jl, in expression starting on line 27
```

Any thoughts?

**Comment by diegozea** [comment]
Hi @kescobo I'm sorry but I haven't updated this packages for Julia 0.6 yet.

**Comment by kescobo** [comment]
@diegozea got it - no worries! Got distracted by other things anyway :-)

**Comment by kescobo** [comment]
I think this is fixed with recent updates? Anyway, it started up for me fine - I'm gonna close for now.

**Comment by diegozea** [comment]
Yes, the last tagged version was updated for working in Julia0.6 and this was fixed ;)
